### ISSUE TITLE
Support for `aarch64-linux`

### ISSUE THREAD

**Issue by koxu1996** [cspr-rad/risc0pkgs#10]
By default `rustc0` is [released](https://github.com/risc0/rust/releases) for the following platforms:

* `aarch64-apple-darwin`
* `x86_64-apple-darwin`
* `x86_64-unknown-linux-gnu`

In risc0pkgs, `x86_64-unknown-linux-gnu` is used for all Linux machines:

https://github.com/cspr-rad/risc0pkgs/blob/7acff27ce7116777cc7f5a162efa9b599808ed97/pkgs/rustc0/default.nix#L47-L54

I would like to make it compatible with  `aarch64-linux`.

**Comment by koxu1996** [comment]
I was able to compile toolchain for `aarch64-linux`, by running the following commands on my Asahi M2 machine:

```
$ cargo install cargo-binstall
$ cargo binstall cargo-risczero
$ sudo pacman -S cmake
$ cargo risczero build-toolchain
$ cd ~/.risc0/rust/build/aarch64-unknown-linux-gnu/stage2/
$ GZIP=-9 tar -czvf /tmp/rust-toolchain-aarch64-unknown-linux-gnu.tar.gz .
```

Here is [rust-toolchain-aarch64-unknown-linux-gnu.tar.gz](https://drive.google.com/file/d/1A9shvA3eDklvfQylwWDE4CrTxX-k1oyb/view?usp=sharing) (**393 MiB**, sha256: _d9c6a874994adc3dbd5af275d0a4a4672792c099a8bc6358406da0073dc95297_).

**Comment by marijanp** [comment]
Added in #13
